### ISSUE TITLE
Error with codec after "finish where"

### ISSUE THREAD

**Issue by GribanovaM** [kartverket/where#8] opened 2020-12-18 09:09 UTC
Good morning,

I have successfully installed the program ( v1.1.0) on my PC (i use Linux), but i have an error after finish where and i can`t understand what causes it.  
Content of log file is presented below. Could You please help me to fix it or give some advice?
Thank you in advance for your assistance.

INFO   2020-12-17 15:12:05 [VLBI XA 2018-01-02] Start plug-in 'vlbi.read' in 'where.pipelines'
INFO   2020-12-17 15:12:05 [VLBI XA 2018-01-02] Reading observation file in vgosdb format
INFO   2020-12-17 15:12:08 [VLBI XA 2018-01-02] Session code: R1823
INFO   2020-12-17 15:12:09 [VLBI XA 2018-01-02] Found stations: FORTLEZA, HART15M, ISHIOKA, KATH12M, KOKEE, NYALES20, WETTZ13N, YARRA12M
INFO   2020-12-17 15:12:21 [VLBI XA 2018-01-02] Parsed 3390 observations

INFO   2020-12-17 15:12:21 [VLBI XA 2018-01-02] Start plug-in 'vlbi.edit' in 'where.pipelines'
INFO   2020-12-17 15:12:21 [VLBI XA 2018-01-02] Applying editors
INFO   2020-12-17 15:12:21 [VLBI XA 2018-01-02] analysis_status: Setting status to 'unchecked'
INFO   2020-12-17 15:12:21 [VLBI XA 2018-01-02] Applying removers
INFO   2020-12-17 15:12:21 [VLBI XA 2018-01-02] Removing     0 observations based on elevation
INFO   2020-12-17 15:12:21 [VLBI XA 2018-01-02] Removing     0 observations based on ignore_epochs
INFO   2020-12-17 15:12:21 [VLBI XA 2018-01-02] Removing     0 observations based on ignore_observation
INFO   2020-12-17 15:12:21 [VLBI XA 2018-01-02] Removing     0 observations based on ignore_station
INFO   2020-12-17 15:12:21 [VLBI XA 2018-01-02] Removing   398 observations based on vlbi_data_quality
INFO   2020-12-17 15:12:21 [VLBI XA 2018-01-02] Removing     0 observations based on vlbi_ignore_baseline
INFO   2020-12-17 15:12:21 [VLBI XA 2018-01-02] Removing     0 observations based on vlbi_ignore_nan
INFO   2020-12-17 15:12:22 [VLBI XA 2018-01-02] Removing     0 observations based on vlbi_ignore_source
INFO   2020-12-17 15:12:22 [VLBI XA 2018-01-02] Removing     0 observations based on vlbi_iono_quality
INFO   2020-12-17 15:12:22 [VLBI XA 2018-01-02] Keeping 2992 of 3390 observations

INFO   2020-12-17 15:12:22 [VLBI XA 2018-01-02] Start plug-in 'vlbi.calculate' in 'where.pipelines'
INFO   2020-12-17 15:12:22 [VLBI XA 2018-01-02] Calculating station displacements
INFO   2020-12-17 15:12:42 [VLBI XA 2018-01-02] Finish pipeline VLBI in 36.7345 seconds
INFO   2020-12-17 15:12:42 [VLBI XA 2018-01-02] Finish where in 38.7062 seconds
ERROR  2020-12-17 15:12:42 [VLBI XA 2018-01-02] 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by annsilje** [comment] 2020-12-18 10:17
Hi,

I think I have seen this problem before. This is a most likely caused by a bug in the companion library Midgard. If you upgrade that library to version 1.1.2 this problem should be fixed. I think version 1.1.1 is installed by default. The problem is related to reading a specific file so you may have to delete that file and allow the program to download it again from scratch. As a tip you can always run Where with the flag -T to get a full traceback when something goes wrong. If you do that you should get information about which file is causing problems.

**Closed as completed** 2021-02-26 07:41 UTC
